### ISSUE TITLE
Interface for creating "travel" posts

### ISSUE THREAD

**Issue by aaronpk** [aaronpk/p3k#39]
Here is the data used to render one of my "travel" posts:

```yaml
title: Ontario to Portland
date: "2014-01-10T09:55:00-0800"
timezone: America/Los_Angeles
type: flight
tags: esri
legs:
  - depart: 
      date: "2014-01-10T09:55:00-0800"
      airport: ONT
    arrive: 
      date: "2014-01-10T12:18:00-1000"
      airport: PDX
    seat: 5D
    airline: Alaska
    flight: 3463
```

http://aaronparecki.com/travel/2014/01/10/1/

For a multi-leg trip, it looks like this:

```yaml
title: Dubai to Portland
date: "2013-11-22T01:55:00+0400"
timezone: GST
type: flight
tags: esri, devsummit
legs:
  - depart: 
      date: "2013-11-22T01:55:00+0400"
      airport: DXB
    arrive: 
      date: "2013-11-22T06:15:00+0100"
      airport: AMS
    seat: 27F
    airline: KLM
    flight: 428
  - depart: 
      date: "2013-11-22T10:00:00+0100"
      airport: AMS
    arrive: 
      date: "2013-11-22T11:30:00-0800"
      airport: PDX
    seat: 21A
    airline: KLM
    flight: 6009
```

http://aaronparecki.com/travel/2013/11/22/1/
